import React, { useState, useEffect } from 'react';

const WannaCryMockup = () => {
  const [timeLeft, setTimeLeft] = useState(72 * 60 * 60); // 3 days in seconds
  const [timeRaised, setTimeRaised] = useState(168 * 60 * 60); // 7 days in seconds
  
  useEffect(() => {
    const timer = setInterval(() => {
      setTimeLeft((prevTime) => (prevTime > 0 ? prevTime - 1 : 0));
      setTimeRaised((prevTime) => (prevTime > 0 ? prevTime - 1 : 0));
    }, 1000);
    
    return () => clearInterval(timer);
  }, []);
  
  const formatTime = (seconds: number) => {
    const days = Math.floor(seconds / (3600 * 24));
    const hours = Math.floor((seconds % (3600 * 24)) / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;
    
    return `${days.toString().padStart(2, '0')}d:${hours.toString().padStart(2, '0')}h:${minutes.toString().padStart(2, '0')}m:${secs.toString().padStart(2, '0')}s`;
  };
  
  const backgroundStyle = {
    backgroundImage: `
      repeating-linear-gradient(
        rgba(0, 0, 0, 0.95),
        rgba(0, 0, 0, 0.95)
      ),
      linear-gradient(
        to right,
        rgba(0, 0, 0, 0.9),
        rgba(0, 0, 0, 0.9)
      )
    `,
    backgroundSize: 'cover',
    position: 'relative' as const,
    overflow: 'hidden'
  };
  
  const textOverlayStyle = {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
    pointerEvents: 'none' as const,
    zIndex: 0,
    lineHeight: '2rem'
  };
  
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-black text-red-600 p-4" style={backgroundStyle}>
      {/* Background text overlay */}
      <div style={textOverlayStyle} className="text-5xl font-mono opacity-20">
        <div className="transform -rotate-12 -translate-y-64 -translate-x-4">
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
          Oops, your files have been encrypted... Wanna Decrypt0r... windows... antivirus... 
          your computer... need your files... payment... bitcoin software... 
          find an appropriate... Bitcoin address... wanna.decryptor@...
          follow the instructions!... payment... encryption... 
          files are encrypted... Wanna Decrypt0r... windows... antivirus...
        </div>
      </div>
      
      {/* Main content area */}
      <div className="max-w-2xl w-full flex flex-col z-10">
        {/* Window title bar */}
        <div className="bg-gray-200 px-2 py-1 flex justify-between items-center">
          <div className="flex items-center">
            <span className="text-black text-sm">Ransomware</span>
          </div>
          <div className="flex">
            <span className="px-2">_</span>
            <span className="px-2">□</span>
            <span className="px-2">×</span>
          </div>
        </div>
        
        <div className="flex">
          {/* Left side - Red background */}
          <div className="bg-red-700 p-4 w-1/3 flex flex-col items-center text-center">
            <div className="bg-gray-200 p-4 mb-4 rounded">
              <div className="w-16 h-16 mx-auto mb-2">
                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <rect x="5" y="11" width="14" height="10" fill="#c53030" stroke="white" strokeWidth="2"/>
                  <path d="M7 11V7C7 4.23858 9.23858 2 12 2C14.7614 2 17 4.23858 17 7V11" stroke="white" strokeWidth="2"/>
                  <circle cx="12" cy="16" r="2" fill="white"/>
                </svg>
              </div>
            </div>
            
            <p className="text-yellow-300 font-bold mb-2">Payment will be raised on</p>
            <p className="mb-2 text-white">4/7/2025 17:00:00</p>
            <p className="text-sm mb-1 text-white">Time Left</p>
            <div className="bg-black text-lg font-mono p-2 w-full mb-4 text-white">
              {formatTime(timeRaised)}
            </div>
            
            <p className="text-yellow-300 font-bold mb-2">Your files will be lost on</p>
            <p className="mb-2 text-white">4/4/2025 17:00:00</p>
            <p className="text-sm mb-1 text-white">Time Left</p>
            <div className="bg-black text-lg font-mono p-2 w-full mb-4 text-white">
              {formatTime(timeLeft)}
            </div>
            
            <div className="mt-4">
              <button className="bg-blue-800 text-white p-1 text-sm mb-2 w-full">About bitcoin</button>
              <button className="bg-blue-800 text-white p-1 text-sm mb-2 w-full">How to buy bitcoins?</button>
              <button className="bg-blue-800 text-white p-1 text-sm w-full">Contact Us</button>
            </div>
          </div>
          
          {/* Right side - Main content */}
          <div className="bg-white text-black p-4 w-2/3">
            <div className="flex justify-between items-center mb-4">
              <h1 className="text-red-700 text-lg font-bold">You've got mail!</h1>
              <select className="border border-gray-400 text-sm p-1">
                <option>English</option>
              </select>
            </div>
            
            <div className="mb-4">
              <h2 className="font-bold mb-1">What Happened to My Computer?</h2>
              <p className="text-sm mb-2">Your important files are encrypted.</p>
              <p className="text-sm mb-2">Many of your documents, photos, videos, databases and other files are no longer accessible because they have been encrypted. Maybe you are busy looking for a way to recover your files, but do not waste your time. Nobody can recover your files without our decryption service.</p>
            </div>
            
            <div className="mb-4">
              <h2 className="font-bold mb-1">Can I Recover My Files?</h2>
              <p className="text-sm mb-2">Sure. We guarantee that you can recover all your files safely and easily. But you have not so enough time.</p>
              <p className="text-sm mb-2">You can decrypt some of your files for free. Try now by clicking «Decrypt».</p>
              <p className="text-sm mb-2">But if you want to decrypt all your files, you need to pay.</p>
              <p className="text-sm mb-2">You only have 3 days to submit the payment. After that the price will be doubled.</p>
              <p className="text-sm mb-2">Also, if you don't pay in 7 days, you won't be able to recover your files forever.</p>
              <p className="text-sm mb-2">We will have free events for users who are so poor that they couldn't pay in 6 months.</p>
            </div>
            
            <div className="mb-4">
              <h2 className="font-bold mb-1">How Do I Pay?</h2>
              <p className="text-sm mb-2">Payment is accepted in Bitcoin only. For more information, click «About bitcoin».</p>
              <p className="text-sm mb-2">Please check the current price of Bitcoin and buy some bitcoins. For more information, click «How to buy bitcoins».</p>
              <p className="text-sm mb-2">And send the correct amount to the address specified in this window.</p>
              <p className="text-sm mb-2">After your payment, click «Check Payment». Best time to check: 9:00am - 11:00am GMT+1</p>
            </div>
            
            <div className="bg-yellow-200 p-2 mb-4">
              <p className="text-sm font-bold">Send $500 worth of bitcoin to this address:</p>
              <div className="flex">
                <input 
                  type="text" 
                  className="border border-gray-400 p-1 w-full bg-gray-100" 
                  value="1ABYDFgwuz23HyMgw51Sp7AABicjrSSWur" 
                  readOnly 
                />
                <button className="bg-gray-300 px-2">Copy</button>
              </div>
            </div>
            
            <div className="flex justify-around">
              <button className="bg-blue-500 text-white px-8 py-2">Check Payment</button>
              <button className="bg-gray-300 px-8 py-2">Decrypt</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default WannaCryMockup;